// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxnigenudzuigoygbipe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4bmlnZW51ZHp1aWdveWdiaXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDI2MzQsImV4cCI6MjA1NzYxODYzNH0.YJ6OqaGGj88q6v7P5LB8Iub-2VqqBJkXUxDZsnStYJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);